<?php
require_once('PlurkAlertsSetting.php');
require_once('PlurkBlocksSetting.php');
require_once('PlurkCliquesSetting.php');
require_once('PlurkEmoticonsSetting.php');
require_once('PlurkFriendsFansSetting.php');
require_once('PlurkPollingSetting.php');
require_once('PlurkProfileSetting.php');
require_once('PlurkRealtimeSetting.php');
require_once('PlurkResponsesSetting.php');
require_once('PlurkSearchSetting.php');
require_once('PlurkSetting.php');
require_once('PlurkTimelineSetting.php');
require_once('PlurkUsersSetting.php');
?>